### PR TITLE
hotfix(get-swaggerdoc) : #17 Fixed get swagger doc for api

### PR DESCRIPTION
**Pull request by kand617**
Fix for issue #17 .

### CODE REVIEW

**Comment by kand617** [comment]
@sudhirtumati CI having issues?

**Comment by sudhirtumati** [comment]
@kand617 seems there is an issue with maven repository connectivity. See [travis docs](https://docs.travis-ci.com/user/common-build-problems/#My-builds-are-timing-out) for more details on this. May be we can wait for a day and see if issue persists

**Comment by kand617** [comment]
Odd, it gets stuck when requesting this file:
https://repository.apache.org/releases/org/springframework/cloud/spring-cloud-dependencies/Finchley.RC1/spring-cloud-dependencies-Finchley.RC1.pom

This is giving me a 404 on my PC

**Comment by sudhirtumati** [comment]
It seems their connectivity issues are resolved now. Builds are ok

**Pull request merged**
